TARGETS = A.txt B.txt C.txt actor.txt

all: $(TARGETS)
A.txt : ThreeThread.txt
	java -jar ../../../utah01/dist/utah01.jar ThreeThread.txt
B.txt : ThreeThread.txt
	java -jar ../../../utah01/dist/utah01.jar ThreeThread.txt
C.txt : ThreeThread.txt
	java -jar ../../../utah01/dist/utah01.jar ThreeThread.txt
actor.txt : ThreeThread.txt
	java -jar ../../../utah01/dist/utah01.jar ThreeThread.txt
