TARGETS = CRUISECONTROLLER.txt INPUTSPEED.txt SENSORSCAN.txt SPEC.txt SPEEDCONTROL.txt 

all: $(TARGETS)
CRUISECONTROLLER.txt : CruiseControl.txt
	java -jar ../../utah01/dist/utah01.jar CruiseControl.txt
INPUTSPEED.txt : CruiseControl.txt
	java -jar ../../utah01/dist/utah01.jar CruiseControl.txt
SENSORSCAN.txt : CruiseControl.txt
	java -jar ../../utah01/dist/utah01.jar CruiseControl.txt
SPEC.txt : CruiseControl.txt
	java -jar ../../utah01/dist/utah01.jar CruiseControl.txt
SPEEDCONTROL.txt : CruiseControl.txt
	java -jar ../../utah01/dist/utah01.jar CruiseControl.txt
